name: Gerar Release da Master

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Poetry
        run: pipx install poetry

      - name: Read pyproject.toml version
        id: poetry_version
        run: |
          VERSION=$(poetry version -s)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Run Tests
        run: poetry run pytest

      - name: Create GitHub Release e Automatic Tag
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.poetry_version.outputs.VERSION }}
          name: Release ${{ steps.poetry_version.outputs.VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Build
        run: poetry build